import "../styles/globals.css"
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import Navbar from "@/containers/Navbar/Navbar";
import AuthProvider from "@/components/AuthProvider/AuthProvider";
import Footer from "@/containers/Footer/Footer";
const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Tienda Web",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <AuthProvider>
          <Navbar />
          <main>{children}</main>
         <Footer/>
        </AuthProvider>
      </body>
    </html>
  );
}
